config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end

  def new
  	@product = Product.new
  end

  def create
  @product = Product.new(product_params)
  if @product.save
  	redirect_to root_path
  end
  end

  private def product_params
  params.require(:product).permit(:shopname, :title, :description)
  end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>
<%= link_to "Create Product", new_product_path %>

app/views/products/new.html.erb
<%= form_for @product do |f| %>
<%= f.label :shopname %>
<%= f.text_field :shopname %><br/>
<%= f.label :title %>
<%= f.text_field :title %><br/>
<%= f.label :description %>
<%= f.text_field :description %><br/>
<%= f.submit %>
<% end %>